"""create deals

Revision ID: 241e05a0e18f
Revises: bd0b0572923d
Create Date: 2026-08-11 15:49:05.060832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241e05a0e18f'
down_revision: Union[str, Sequence[str], None] = 'bd0b0572923d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('project_type_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('deal_status_id', sa.Integer(), nullable=False),
    sa.Column('platform_external_id', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=255), nullable=True),
    sa.Column('contact_description', sa.Text(), nullable=True),
    sa.Column('budget', sa.String(length=255), nullable=True),
    sa.Column('meeting_time', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('external_lead_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status_meeting_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_status_id'], ['deal_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['deal_platforms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_meeting_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_assigned_to'), 'deals', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_deal_status_id'), 'deals', ['deal_status_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_platform_id'), 'deals', ['platform_id'], unique=False)
    op.create_index(op.f('ix_deals_project_type_id'), 'deals', ['project_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_project_type_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_platform_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_status_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_assigned_to'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
