"""create company api keys

Revision ID: 43fc15317203
Revises: e3ef0401e7b5
Create Date: 2026-08-07 15:15:32.236834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fc15317203'
down_revision: Union[str, Sequence[str], None] = 'e3ef0401e7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_api_keys_company_id'), 'company_api_keys', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_api_keys_id'), 'company_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_company_api_keys_key_prefix'), 'company_api_keys', ['key_prefix'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_api_keys_key_prefix'), table_name='company_api_keys')
    op.drop_index(op.f('ix_company_api_keys_id'), table_name='company_api_keys')
    op.drop_index(op.f('ix_company_api_keys_company_id'), table_name='company_api_keys')
    op.drop_table('company_api_keys')
    # ### end Alembic commands ###
