"""add company billing snapshot to invoices

Revision ID: 5de4322f2d37
Revises: 8922ce580add
Create Date: 2026-08-20 12:44:11.189776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de4322f2d37'
down_revision: Union[str, Sequence[str], None] = '8922ce580add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'invoices',
    sa.Column('company_name', sa.String(length=255), nullable=True)
)

    op.execute("""
        UPDATE invoices
        SET company_name = companies.name
        FROM companies
        WHERE invoices.company_id = companies.id
    """)

    op.alter_column(
        'invoices',
        'company_name',
        existing_type=sa.String(length=255),
        nullable=False,
    )
    op.add_column('invoices', sa.Column('company_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('company_state', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('company_state_code', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('company_gstin', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'company_gstin')
    op.drop_column('invoices', 'company_state_code')
    op.drop_column('invoices', 'company_state')
    op.drop_column('invoices', 'company_address')
    op.drop_column('invoices', 'company_name')
    # ### end Alembic commands ###
