"""create salary structures

Revision ID: 5e060fea0929
Revises: 0536ffd0c7f8
Create Date: 2026-08-17 15:48:47.184360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e060fea0929'
down_revision: Union[str, Sequence[str], None] = '0536ffd0c7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_code'), 'salary_structures', ['code'], unique=False)
    op.create_index(op.f('ix_salary_structures_company_id'), 'salary_structures', ['company_id'], unique=False)
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_table('salary_structure_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('salary_component_id', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.Integer(), nullable=False),
    sa.Column('calculation_base', sa.Integer(), nullable=True),
    sa.Column('calculation_base_component_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_base_component_id'], ['salary_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_component_id'], ['salary_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary_structure_id', 'salary_component_id', name='uq_salary_structure_component')
    )
    op.create_index(op.f('ix_salary_structure_components_calculation_base_component_id'), 'salary_structure_components', ['calculation_base_component_id'], unique=False)
    op.create_index(op.f('ix_salary_structure_components_id'), 'salary_structure_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_structure_components_salary_component_id'), 'salary_structure_components', ['salary_component_id'], unique=False)
    op.create_index(op.f('ix_salary_structure_components_salary_structure_id'), 'salary_structure_components', ['salary_structure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structure_components_salary_structure_id'), table_name='salary_structure_components')
    op.drop_index(op.f('ix_salary_structure_components_salary_component_id'), table_name='salary_structure_components')
    op.drop_index(op.f('ix_salary_structure_components_id'), table_name='salary_structure_components')
    op.drop_index(op.f('ix_salary_structure_components_calculation_base_component_id'), table_name='salary_structure_components')
    op.drop_table('salary_structure_components')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_company_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_code'), table_name='salary_structures')
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
