"""create payroll and payroll items

Revision ID: 6a3b67d1fc09
Revises: bc68c3eff72f
Create Date: 2026-08-18 11:35:07.833353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3b67d1fc09'
down_revision: Union[str, Sequence[str], None] = 'bc68c3eff72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payroll_month', sa.Integer(), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'payroll_month', 'payroll_year', name='uq_payroll_user_period')
    )
    op.create_index(op.f('ix_payrolls_company_id'), 'payrolls', ['company_id'], unique=False)
    op.create_index(op.f('ix_payrolls_id'), 'payrolls', ['id'], unique=False)
    op.create_index(op.f('ix_payrolls_user_id'), 'payrolls', ['user_id'], unique=False)
    op.create_table('payroll_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('salary_component_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('component_type', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.Integer(), nullable=False),
    sa.Column('calculation_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_component_id'], ['salary_components.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_id', 'salary_component_id', name='uq_payroll_component')
    )
    op.create_index(op.f('ix_payroll_items_id'), 'payroll_items', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_items_payroll_id'), 'payroll_items', ['payroll_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_salary_component_id'), 'payroll_items', ['salary_component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_items_salary_component_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_payroll_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_id'), table_name='payroll_items')
    op.drop_table('payroll_items')
    op.drop_index(op.f('ix_payrolls_user_id'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_id'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_company_id'), table_name='payrolls')
    op.drop_table('payrolls')
    # ### end Alembic commands ###
