"""add company billing gst fields

Revision ID: 8922ce580add
Revises: 05cf0d263019
Create Date: 2026-08-19 18:59:51.140023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8922ce580add'
down_revision: Union[str, Sequence[str], None] = '05cf0d263019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('state_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'state_code')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'gst_number')
    op.drop_column('companies', 'company_address')
    # ### end Alembic commands ###
