"""create employee salaries

Revision ID: bc68c3eff72f
Revises: 5e060fea0929
Create Date: 2026-08-17 17:41:53.289012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc68c3eff72f'
down_revision: Union[str, Sequence[str], None] = '5e060fea0929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salaries_effective_from'), 'employee_salaries', ['effective_from'], unique=False)
    op.create_index(op.f('ix_employee_salaries_effective_to'), 'employee_salaries', ['effective_to'], unique=False)
    op.create_index(op.f('ix_employee_salaries_id'), 'employee_salaries', ['id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_salary_structure_id'), 'employee_salaries', ['salary_structure_id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_user_id'), 'employee_salaries', ['user_id'], unique=False)
    op.create_index('ix_employee_salary_user_effective', 'employee_salaries', ['user_id', 'effective_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_salary_user_effective', table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_user_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_salary_structure_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_effective_to'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_effective_from'), table_name='employee_salaries')
    op.drop_table('employee_salaries')
    # ### end Alembic commands ###
