"""add auto closed to attendance sessions

Revision ID: d1e8c5356a36
Revises: 27cac535df95
Create Date: 2026-08-17 11:58:55.787795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e8c5356a36'
down_revision: Union[str, Sequence[str], None] = '27cac535df95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('auto_closed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_sessions', 'auto_closed')
    # ### end Alembic commands ###
