"""add profile image to users

Revision ID: dc73b292a46a
Revises: 122a5114d677
Create Date: 2026-08-07 11:34:18.722171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc73b292a46a'
down_revision: Union[str, Sequence[str], None] = '122a5114d677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
